# name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Setup PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'

#     # - name: Install dependencies
#     #   run: |
#     #     cd /var/www/prod/Lms
#     #     composer install --ignore-platform-req=ext-mongodb

#     # - name: Run tests
#     #   run: |
#     #     cd /var/www/prod/Lms
#     #     phpunit

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - name: Setup SSH
#       uses: webfactory/ssh-agent@v0.5.1
#       with:
#         ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

#     - name: Deploy to EC2
#       run: |
#         cd /var/www/prod/Lms
#         git pull origin master
name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create project directory (if not exists)
      run: mkdir -p /var/www/prod/Lms

    - name: Navigate to project directory
      run: cd /var/www/prod/Lms

    - name: Print current working directory
      run: pwd

    - name: Print directory contents
      run: ls -l

    - name: Git pull
      run: git pull origin master

