# name: CI/CD

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'

#     - name: Take Pull from Master
#       run:  git pull origin master
#     - name: Install Composer Dependencies
#       run: composer install --prefer-dist --no-progress --no-suggest

#     - name: Deploy Your Laravel Application (Adjust as Needed)
#       run: |
#         php artisan optimize
name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Environment Information
      run: |
        echo "GitHub Actions Environment:"
        env
        echo "Current User:"
        whoami
        echo "Current Working Directory:"
        pwd

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Create Deployment Directory
      run: |
        sudo mkdir -p /var/www/prod/Lms
        sudo chown -R $USER:$USER /var/www/prod/Lms
        echo "Deployment directory created and permissions set."

    - name: Deploy Your Laravel Application
      run: |
        rsync -av --exclude=.git --exclude=vendor . /var/www/prod/Lms
        echo "Code deployed to /var/www/prod/Lms."
        echo "Contents of /var/www/prod/Lms:"
        ls -la /var/www/prod/Lms


