# name: CI/CD

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Set up PHP
#       uses: shivammathur/setup-php@v2
#       with:
#         php-version: '8.1'

#     - name: Take Pull from Master
#       run:  git pull origin master
#     - name: Install Composer Dependencies
#       run: composer install --prefer-dist --no-progress --no-suggest

#     - name: Deploy Your Laravel Application (Adjust as Needed)
#       run: |
#         php artisan optimize
name: CI/CD Laravel Project

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            # Now we have access to the EC2 instance, perform deployment steps.
            cd /var/www/prod/Lms &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            composer install --no-interaction --prefer-dist &&
          '
